services:
  - type: web
    name: zero630proxy
    env: node
    buildCommand: |
      apt-get update
      apt-get install -y wget gnupg ca-certificates
      wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | apt-key add -
      sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
      apt-get update
      apt-get install -y google-chrome-stable
      npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
