services:
  - type: web
    name: zero630proxy
    env: node
    buildCommand: "npm install && npx playwright install --with-deps"
    startCommand: "node index.js"
    envVars:
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: true
